### ISSUE TITLE
feature request for a ValueSortedDictWithKey

### ISSUE THREAD

**Issue by basnijholt** [grantjenks/sortedcollections#1]
Hi there, I'm using your `sortedcontainers` package and want to have a `SortedDict` by value where the values are objects.

for example in an integration routine:
```python
ValueSortedDictWithKey({(i.a, i.b): i for i in intervals(f, a, b, tol)}, key=operator.attrgetter('err'))
```
here the intervals have bounds `a` and `b`, and a certain error `err` associated with them, I would like to sort by the error.

Is this possible?

**Comment by grantjenks** [comment]
That should work but put the key function first as a positional argument: ValueSortedDict(key_func, mapping)
